### ISSUE TITLE
Unable to instantiate xdebug

### ISSUE THREAD

**Issue by panosru** [prooph/proophessor-do#161]
Hello,

I have hard time to instantiate xdebug for proophessor-do.

I have cloned the project and added it to Phpstorm projects in order to be able to put some break-points and see exactly the route it takes for each functionality in order to better understand prooph components.

for `docker-compose.yml` I changed the `php` section into this:

```yml
  php:
    image: prooph/php:7.1-fpm-xdebug
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - mongodb
    environment:
      - PROOPH_ENV=development
      - XDEBUG_CONFIG="remote_host=192.168.1.9"
      - PHP_IDE_CONFIG="serverName=Prooph-docker"
```
everything else is default

For the phpstorm part:

DBGp Proxy settings:
[![enter image description here][1]][1]

Server settings:
[![enter image description here][2]][2]

Run/Debug Configurations (docker)
[![enter image description here][3]][3]

Run/Debug Configurations (PHP Remote Debug)
[![enter image description here][4]][4]
I have tried also with checked Filter.. checkbox

my `ifconfig` result:
```bash
 ~ $ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC0: flags=0<> mtu 0
EHC250: flags=0<> mtu 0
EHC253: flags=0<> mtu 0
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=b<RXCSUM,TXCSUM,VLAN_HWTAGGING>
	ether c4:2c:03:24:83:a0
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (none)
	status: inactive
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 60:33:4b:0b:61:83
	inet6 fe80::cc9:38d4:7cf:1b54%en1 prefixlen 64 secured scopeid 0x8
	inet 192.168.1.9 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 02:33:4b:0b:61:83
	media: autoselect
	status: inactive
fw0: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 4078
	lladdr e8:06:88:ff:fe:f0:eb:0e
	media: autoselect <full-duplex>
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::249a:d86c:ab3e:6e1a%utun0 prefixlen 64 scopeid 0xb
	nd6 options=201<PERFORMNUD,DAD>
```

When I run `Docker` from PhpStorm:
[![enter image description here][5]][5]

When I run the debugger from PhpStorm:
[![enter image description here][6]][6]

And still, breakpoints are getting ignored...

I probably miss something on the way, but I'm not sure what is it.

This is my phpinfo() for the xdebug section:
[![enter image description here][7]][7]

And this is the Environment section from phpinfo()
[![enter image description here][9]][9]

I saw here that the IDE Key is set on www-data, and I set www-data as the IDE key to listen for in PhpStorm, but still nothing happened...
[![enter image description here][8]][8]

Also, it is my first time using docker, I never used it before. I used to use virtual box for mac, and my remote debug worked fine, so I guess the steps to follow with docker are more or less the same.. no?

As @codeliner suggested I'm pinging @sandrokeil  on this.

Thanks!

  [1]: https://i.stack.imgur.com/o3KeS.png
  [2]: https://i.stack.imgur.com/o3KeS.png
  [3]: https://i.stack.imgur.com/qPGiW.png
  [4]: https://i.stack.imgur.com/9DHpD.png
  [5]: https://i.stack.imgur.com/QBRgX.png
  [6]: https://i.stack.imgur.com/WvNRy.png
  [7]: https://i.stack.imgur.com/7hdQX.png
  [8]: https://i.stack.imgur.com/ZrOaK.png
  [9]: https://i.stack.imgur.com/Goyiz.png

**Comment by sandrokeil** [comment]
You are using a Mac or? Any Mac Users here who could help?

**Comment by panosru** [comment]
@sandrokeil Yes I'm on mac, sorry I forgot to clarify that.

**Comment by panosru** [comment]
After some more checking I saw that in phpinfo() the remote host ip was still on localhost and the path mapping on phpstorm wasn't correct.

I changed this:
```yml
  php:
    image: prooph/php:7.1-fpm-xdebug
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - mongodb
    environment:
      - PROOPH_ENV=development
      - XDEBUG_CONFIG="remote_host=192.168.1.9"
      - PHP_IDE_CONFIG="serverName=Prooph-docker"
```
into this
```yml
  php:
    image: prooph/php:7.1-fpm-xdebug
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - mongodb
    environment:
      PROOPH_ENV: "development"
      XDEBUG_CONFIG: "remote_host=192.168.1.9"
      PHP_IDE_CONFIG: "serverName=Prooph-docker"
```

now my phpinfo() looks correct:
[![enter image description here][1]][1]
[![enter image description here][2]][2]


And I mapped `./public` to `/var/www`
[![enter image description here][3]][3]

Still not working... so I thought to add `./etc/xdebug-custom.ini` file that contains:
```ini
[xdebug]
xdebug.remote_enable=On
xdebug.idekey=PHPSTORM
xdebug.profiler_enable=0
xdebug.max_nesting_level=700
xdebug.remote_host=192.168.1.9
xdebug.remote_port=10000
xdebug.remote_autostart=off
```

and change my `docker-compose.yml` in `php` service:
```yml
  php:
    image: prooph/php:7.1-fpm-xdebug
    volumes:
      - "./etc/xdebug-custom.ini:/usr/local/etc/php/conf.d/xdebug-custom.ini"
      - .:/var/www
    depends_on:
      - mysql
      - mongodb
    environment:
      PROOPH_ENV: "development"
      XDEBUG_CONFIG: "remote_host=192.168.1.9"
      PHP_IDE_CONFIG: "serverName=Prooph-docker"
```

restart the containers, `phpinfo()` looks fine, with all the custom settings in place but debug still not working...

I moved all the projects that I have locally from MAMP Pro to docker, and I setup the debugger and it works fine, is not working only for that repo, really not sure what to do next.

Thanks

  [1]: https://i.stack.imgur.com/IMK6F.png
  [2]: https://i.stack.imgur.com/d22m9.png
  [3]: https://i.stack.imgur.com/tPYfO.png

**Comment by panosru** [comment]
I'm putting some update on the issue (still not solved).

So in order to see what's going on I had to put a log file into the container.

My `docker-compose.yml` file look like this:
```yml
  php:
    image: prooph/php:7.1-fpm-xdebug
    restart: always
    volumes:
      - ./etc/xdebug.log:/tmp/xdebug.log
      - "./etc/xdebug-custom.ini:/usr/local/etc/php/conf.d/xdebug-custom.ini"
      - .:/var/www
    depends_on:
      - mysql
      - mongodb
    environment:
      PROOPH_ENV: "development"
      XDEBUG_CONFIG: "remote_connect_back=0"
      PHP_IDE_CONFIG: "serverName=prooph-docker"
      PHP_XDEBUG_ENABLED: 1
```

and my `xdebug-custom.ini` look like this:
```ini
# PHPStorm
[xdebug]
xdebug.remote_enable=1
xdebug.idekey=PHPSTORM
xdebug.profiler_enable=0
xdebug.max_nesting_level=700
xdebug.remote_host=192.168.1.9
xdebug.remote_port=10000
xdebug.remote_autostart=Off
xdebug.remote_connect_back=0
xdebug.remote_log=/tmp/xdebug.log
xdebug.remote_timeout=10000
```

I also tried to use `sudo ifconfig en0 alias 10.254.254.254 255.255.255.0` as it was a suggested step in other topics where people had issue making xdebug work on mac, but didn't help me.

so the first think I saw in the `xdebug.log` was the following message:
```
Log opened at 2018-03-25 16:43:56
I: Checking remote connect back address.
I: Checking header 'HTTP_X_FORWARDED_FOR'.
I: Checking header 'REMOTE_ADDR'.
I: Remote address found, connecting to 172.19.0.1:10000.
W: Creating socket for '172.19.0.1:10000', poll success, but error: Operation in progress (29).
E: Could not connect to client. :-(
Log closed at 2018-03-25 16:43:56
```

So I set `xdebug.remote_connect_back=0`, for some reason the setting was ignored from the ini file thus I put `XDEBUG_CONFIG: "remote_connect_back=0"` in `docker-compose.yml` file, which worked fine.

Tried with both `192.168.1.9` and `10.254.254.254` but the result was:
```
Log opened at 2018-03-25 16:50:43
I: Connecting to configured address/port: 10.254.254.254:10000.
E: Time-out connecting to client (Waited: 10000 ms). :-(
Log closed at 2018-03-25 16:50:53

Log opened at 2018-03-25 16:52:44
I: Connecting to configured address/port: 192.168.1.9:10000.
E: Time-out connecting to client (Waited: 10000 ms). :-(
Log closed at 2018-03-25 16:52:54
```
The default value for timeout is 200ms, I set it to 10000ms just in case...

**Comment by codeliner** [comment]
Asked on twitter: https://twitter.com/prooph_software/status/977997982623784960
maybe someone can help. Can't reproduce bc linux only ;)

**Comment by nokios** [comment]
You're not telling the xdebug config that it needs to use dbg. I just set up phpstorm with straight up xdebug and that usually works for me.

I'm not in position to attempt to test and replicate. I will be later. I'll check back in a few hours

**Comment by panosru** [comment]
@codeliner Thanks for that! I spend all day today trying to find a solution but I failed :P 

I'm sure it's a simple fix but as usual simple fixes are harder to find! 

The key point is here is that xdebug + phpstorm + docker works fine for me, but for some reason is not working with `prooph/php:7.1-fpm-xdebug` image...

For today I give up as my eyes are in pain now with so many hours in front of the screen... hopefully someone will be able to help as I really want to have in-depth understanding of prooph components and in order to archive that, after reading the docs many times already, I feel that I have to go line by line on the execution process from proophessor-do

**Comment by panosru** [comment]
@nokios, I'm not sure what do you mean, `xdebug.remote_handler` is set to `dbgp`... as I said, in my other instances of docker that I have, it works fine, for some reason, unknown to me, is not working with `prooph/php:7.1-fpm-xdebug` image.

If I miss something, please let me know as I'm desperate to make it work :D 

Thanks!

**Comment by codeliner** [comment]
ah ok, I missed the point that only the prooph images don't work for you :thinking: 
but can't you just compare the images and check what's different? Here is the build script: https://github.com/prooph/docker-files/blob/master/php/7.1-fpm-xdebug

**Comment by panosru** [comment]
@codeliner, sure I'll take a look! Thanks for pointing that out!

For instance, [this](https://github.com/nanoninja/docker-nginx-php-mongo) works just fine for me out of the box.

I'll post here if I have any progress!

**Comment by panosru** [comment]
@codeliner I can't find any serious difference between [prooph/php:7.1-fpm-xdebug](https://github.com/prooph/docker-files/blob/master/php/7.1-fpm-xdebug) and [nanoninja/php-fpm](https://hub.docker.com/r/nanoninja/php-fpm/) that would cause xdebug not to work on `prooph/php:7.1-fpm-xdebug`, I'm gonna call it off for today as I got really dizzy, gonna check it again tomorrow.

This is a screenshot of a bare-bone docker with xdebug that works fine:
[![enter image description here][1]][1]

`php.ini`:
```ini
# PHPStorm
[xdebug]
xdebug.remote_enable=On
xdebug.idekey=PHPSTORM
xdebug.profiler_enable=0
xdebug.max_nesting_level=700
xdebug.remote_host=192.168.1.9
xdebug.remote_port=10000
xdebug.remote_autostart=off
xdebug.remote_log=/tmp/xdebug.log
```

`docker-compose.yml`:
```yml
version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - "8000:80"
            - "3000:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./src:/var/www"
        depends_on:
            - "php"
    php:
        image: nanoninja/php-fpm
        restart: always
        environment:
          XDEBUG_CONFIG: "remote_host=192.168.1.9"
          PHP_IDE_CONFIG: "serverName=docker-server"
        volumes:
          - ./etc/logs/xdebug.log:/tmp/xdebug.log
          - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
          - ./src:/var/www
```
PhpStorm Settings:
[![enter image description here][2]][2]

[![enter image description here][3]][3]

[![enter image description here][4]][4]

I simply run `docker-compose up -d` and then open `localhost:8000` and it works... 

  [1]: https://i.stack.imgur.com/OxxmO.png
  [2]: https://i.stack.imgur.com/MS42r.png
  [3]: https://i.stack.imgur.com/UsTo4.png
  [4]: https://i.stack.imgur.com/ZjvDR.png

**Comment by frankdejonge** [comment]
Sorry if this is a total n00b response, but I don't see any ports exposed for the PHP container. Wouldn't that mean that it's not working because of that?

**Comment by panosru** [comment]
@frankdejonge AFAIK, you don't need to expose ports for PHP in order for xDebug to work... but at that point I'm willing to try anything in order to make it work.

**Comment by rubenrubiob** [comment]
Hi,

For me it was hard to set it up too, because of the configuration of the remote connection. I use `php:7.1-fpm`, but I suppose it will be similar for you.

This is my configuration:

`.env` file:
```dotfile
# Host Local IP (for Xdebug)
HOST_IP=docker.for.mac.localhost

# Server name (for Xdebug in CLI)
PHPSTORM_SERVER_NAME=www.project.localhost
```

The relevant part of my `docker-compose.yml` file, the one that refers to the PHP container:

```yml
    php:
        container_name: project-php
        build:
            context: docker/php7-fpm
            args:
                HOST_IP: ${HOST_IP}
                PHPSTORM_SERVER_NAME: ${PHPSTORM_SERVER_NAME}
        volumes:
            - ./docker/logs/symfony:/var/www/${SYMFONY_APP_NAME}/var/logs:cached
            - ${SYMFONY_APP_PATH}/vendor:/var/www/${SYMFONY_APP_NAME}/vendor:cached
            - ${SYMFONY_APP_PATH}:/var/www/${SYMFONY_APP_NAME}
```

And the relevant part of my `Dockerfile`:

```Dockerfile
FROM php:7.1-fpm

ARG PHPSTORM_SERVER_NAME
ARG HOST_IP

...

# install xdebug
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug
RUN echo "error_reporting = E_ALL" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "display_startup_errors = On" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "display_errors = On" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_connect_back=0" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN echo "xdebug.remote_port=9001" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
RUN printf "xdebug.remote_host=%s" ${HOST_IP} >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN printf '\nexport PHP_IDE_CONFIG="serverName=%s"\n' ${PHPSTORM_SERVER_NAME} >> ~/.bashrc
```

Then, my xdebug configuration in PHPStorm is as follows:

The configuration for xdebug:

![image](https://user-images.githubusercontent.com/9865569/37894010-fbc0c6f8-30dc-11e8-9933-64f7585e2ca1.png)

And the configuration for server —it is a Symfony 3.4 application, it may differ for you—:

![servers](https://user-images.githubusercontent.com/9865569/37894143-8298af88-30dd-11e8-940a-a1f0c0c0796d.png)

Hope it helps!

Regards!

**Comment by panosru** [comment]
@rubenrubiob Thank you for the comment!

I was about to try that today, as I said to @codeliner in Gitter yesterday, building xdebug from pecl should do the trick and you prove me correct as it works now! 

> @codeliner in regards to issue #161 maybe instead of [cloning](https://github.com/prooph/docker-files/blob/fad9c12cf74f84ea52f33b5483ad28e06d631e01/php/7.2-fpm-xdebug#L21) xdebug source and compile it, just to [install pecl extension](https://github.com/nanoninja/php-fpm/blob/cc218983ce49175261366e155dd46c809ab27580/Dockerfile#L44)? Because other than that I don't see any difference that could cause the issue :( 

Thanks again @rubenrubiob for taking the time to help! 

I didn't changed anything from my previous settings, all I did was changing my `docker-compose.yml` and add `Dockerfile` and then run `$ docker-compose up -d` and xdebug now works fine!

`./docker-compose.yml` file *(only php section)*:
```yml
  php:
    image: prooph/php:7.1-fpm
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./etc/xdebug.log:/tmp/xdebug.log
      - "./etc/xdebug-custom.ini:/usr/local/etc/php/conf.d/xdebug-custom.ini"
      - .:/var/www
    depends_on:
      - mysql
      - mongodb
    environment:
      PROOPH_ENV: "development"
      XDEBUG_CONFIG: "remote_connect_back=0"
      PHP_IDE_CONFIG: "serverName=prooph-docker"
      PHP_XDEBUG_ENABLED: 1
```

`./Dockerfile`:
```
FROM php:7.1-fpm

# install xdebug
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug
```

et voilà! xdebug now works! :)
